export const colors = [
  { class: "black", name: "Black", color: "black" },
  { class: "dark-gray", name: "Dark Gray", color: "#2f2f2f" },
  { class: "red", name: "Red", color: "red" },
  { class: "orange", name: "Orange", color: "orange" },
  { class: "yellow", name: "Yellow", color: "yellow" },
  { class: "green", name: "Green", color: "green" },
  { class: "blue", name: "Blue", color: "blue" },
  { class: "purple", name: "Purple", color: "purple" },
  { class: "pink", name: "Pink", color: "pink" },
  { class: "brown", name: "Brown", color: "brown" },
  { class: "white", name: "White", color: "white" },
  { class: "light-gray", name: "Light Gray", color: "lightgray" },
  { class: "dark-red", name: "Dark Red", color: "darkred" },
  { class: "dark-orange", name: "Dark Orange", color: "darkorange" },
  { class: "dark-yellow", name: "Dark Yellow", color: "goldenrod" },
  { class: "dark-green", name: "Dark Green", color: "darkgreen" },
  { class: "dark-blue", name: "Dark Blue", color: "darkblue" },
  { class: "dark-purple", name: "Dark Purple", color: "indigo" },
  { class: "dark-pink", name: "Dark Pink", color: "deeppink" },
  { class: "dark-brown", name: "Dark Brown", color: "saddlebrown" },
];
